### PR TITLE
set Reader to Body

### PR DESCRIPTION
**Pull request by mattn**
bind stdin to Body in the struct. Now it's possible to upload S3 object like below.

```
$ ./aws-sdk-client-go s3 PutObject '{"bucket": "my-upload-test", "key":"ないしょ.txt"} < ないしょ.txt'
```

### CODE REVIEW

**Comment by fujiwara** [comment]
@mattn Thank you! This is a great feature! But, I found a `io.Reader` field that is not named `Body` in another struct. For example [lambda#InvokeAsyncInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda#InvokeAsyncInput).

I want to support these `io.Reader` fields by uniform flags (for example `--bind-input Body=(filename or -)`.

**Comment by mattn** [comment]
Yes, please

**Comment by mattn** [comment]
How can we set not only Body but also ContentType and ContentLength at the same time?

**Comment by fujiwara** [comment]
> How can we set not only Body but also ContentType and ContentLength at the same time?

ContentType can be set into an `Input` struct as below.
```
$ aws-sdk-clent-go s3 PubObject '{"Bucket":"example","Key":"example","ContentType":"text/plain"}' ...
```

But ContentLength cannot be determined before it is read all from stdin.

For example, [PutChunkInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backupstorage#PutChunkInput) has `Data io.Reader` and `Length int64` fields, so we cannot generally decide the length field name.

As an idea, add `--length-field=ContentLength` to set the length after it is read all from stdin.

**Comment by fujiwara** [comment]
I searched `Input` structs that have `io.Reader` and `*Length*` fields from all.

```
2024/05/20 13:47:18 found io.Reader field in backupstorage.NotifyObjectCompleteInput MetadataBlob io.Reader
2024/05/20 13:47:18 found MetadataBlobLength field in backupstorage.NotifyObjectCompleteInput MetadataBlobLength MetadataBlobLength
2024/05/20 13:47:18 found io.Reader field in backupstorage.PutChunkInput Data io.Reader
2024/05/20 13:47:18 found Length field in backupstorage.PutChunkInput Length Length
2024/05/20 13:47:18 found io.Reader field in backupstorage.PutObjectInput InlineChunk io.Reader
2024/05/20 13:47:18 found InlineChunkLength field in backupstorage.PutObjectInput InlineChunkLength InlineChunkLength
2024/05/20 13:47:19 found io.Reader field in ebs.PutSnapshotBlockInput BlockData io.Reader
2024/05/20 13:47:19 found DataLength field in ebs.PutSnapshotBlockInput DataLength DataLength
2024/05/20 13:47:19 found io.Reader field in s3.PutObjectInput Body io.Reader
2024/05/20 13:47:19 found ContentLength field in s3.PutObjectInput ContentLength ContentLength
2024/05/20 13:47:19 found io.Reader field in s3.UploadPartInput Body io.Reader
2024/05/20 13:47:19 found ContentLength field in s3.UploadPartInput ContentLength ContentLength
2024/05/20 13:47:19 found io.Reader field in s3.WriteGetObjectResponseInput Body io.Reader
2024/05/20 13:47:19 found ContentLength field in s3.WriteGetObjectResponseInput ContentLength ContentLength
```

I think the length field can be set automatically by code generation.

**Comment by mattn** [comment]
If there will never be more than one Reader in a struct in the future, I see no problem with the --length-fied flag.

**Comment by fujiwara** [comment]
@mattn Sorry, I've missed committing past. Add co-author by this commit. bf89ea2a37d832b42f479b5bd1a4f91a43c8dab9

**Comment by mattn** [comment]
No prob :+1:

**Pull request closed without merging**
